export const STATUS = {
  PENDING_REVIEW: 'PENDING_REVIEW',
  NEGOTIATING: 'NEGOTIATING',
  CONFIRMED: 'CONFIRMED',
  SENT_TO_PROCUREMENT: 'SENT_TO_PROCUREMENT',
  ORDER_PLACED: 'ORDER_PLACED',
  SHIPPED_FROM_CHINA: 'SHIPPED_FROM_CHINA',
  ARRIVED_NIGERIA: 'ARRIVED_NIGERIA',
  CUSTOMS_CLEARED: 'CUSTOMS_CLEARED',
  READY_FOR_PICKUP: 'READY_FOR_PICKUP',
  PICKED_UP: 'PICKED_UP',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED',
};

export const STATUS_LABEL = {
  PENDING_REVIEW: 'Request received',
  NEGOTIATING: 'Price negotiation',
  CONFIRMED: 'Order confirmed',
  SENT_TO_PROCUREMENT: 'Sent to procurement',
  ORDER_PLACED: 'Ordered from supplier in China',
  SHIPPED_FROM_CHINA: 'Shipped from China',
  ARRIVED_NIGERIA: 'Arrived in Nigeria',
  CUSTOMS_CLEARED: 'Cleared by customs',
  READY_FOR_PICKUP: 'Ready for pickup',
  PICKED_UP: 'Picked up',
  REJECTED: 'Request declined',
  CANCELLED: 'Cancelled',
};

// Logistics steps must happen strictly in this order.
export const LOGISTICS_FLOW = [
  STATUS.SENT_TO_PROCUREMENT,
  STATUS.ORDER_PLACED,
  STATUS.SHIPPED_FROM_CHINA,
  STATUS.ARRIVED_NIGERIA,
  STATUS.CUSTOMS_CLEARED,
  STATUS.READY_FOR_PICKUP,
];

export const NEGOTIABLE = [STATUS.PENDING_REVIEW, STATUS.NEGOTIATING];
